From Coq Require Import ZArith Lia.
Open Scope Z_scope.

(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require HighOrd.
Require bool.Bool.
Require int.Int.
Require int.Abs.
Require int.ComputerDivision.
Require real.Real.
Require real.RealInfix.
Require real.FromInt.
Require map.Map.

Parameter eqb:
  forall {a:Type} {a_WT:WhyType a}, a -> a -> Init.Datatypes.bool.

Axiom eqb'def :
  forall {a:Type} {a_WT:WhyType a},
  forall (x:a) (y:a),
  ((x = y) -> ((eqb x y) = Init.Datatypes.true)) /\
  (~ (x = y) -> ((eqb x y) = Init.Datatypes.false)).

Parameter neqb:
  forall {a:Type} {a_WT:WhyType a}, a -> a -> Init.Datatypes.bool.

Axiom neqb'def :
  forall {a:Type} {a_WT:WhyType a},
  forall (x:a) (y:a),
  (~ (x = y) -> ((neqb x y) = Init.Datatypes.true)) /\
  ((x = y) -> ((neqb x y) = Init.Datatypes.false)).

Parameter zlt: Numbers.BinNums.Z -> Numbers.BinNums.Z -> Init.Datatypes.bool.

Axiom zlt'def :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z),
  ((x < y)%Z -> ((zlt x y) = Init.Datatypes.true)) /\
  (~ (x < y)%Z -> ((zlt x y) = Init.Datatypes.false)).

Parameter zleq:
  Numbers.BinNums.Z -> Numbers.BinNums.Z -> Init.Datatypes.bool.

Axiom zleq'def :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z),
  ((x <= y)%Z -> ((zleq x y) = Init.Datatypes.true)) /\
  (~ (x <= y)%Z -> ((zleq x y) = Init.Datatypes.false)).

Parameter rlt:
  Reals.Rdefinitions.R -> Reals.Rdefinitions.R -> Init.Datatypes.bool.

Axiom rlt'def :
  forall (x:Reals.Rdefinitions.R) (y:Reals.Rdefinitions.R),
  ((x < y)%R -> ((rlt x y) = Init.Datatypes.true)) /\
  (~ (x < y)%R -> ((rlt x y) = Init.Datatypes.false)).

Parameter rleq:
  Reals.Rdefinitions.R -> Reals.Rdefinitions.R -> Init.Datatypes.bool.

Axiom rleq'def :
  forall (x:Reals.Rdefinitions.R) (y:Reals.Rdefinitions.R),
  ((x <= y)%R -> ((rleq x y) = Init.Datatypes.true)) /\
  (~ (x <= y)%R -> ((rleq x y) = Init.Datatypes.false)).

(* Why3 assumption *)
Definition real_of_int (x:Numbers.BinNums.Z) : Reals.Rdefinitions.R :=
  BuiltIn.IZR x.

Axiom c_euclidian :
  forall (n:Numbers.BinNums.Z) (d:Numbers.BinNums.Z), ~ (d = 0%Z) ->
  (n = (((ZArith.BinInt.Z.quot n d) * d)%Z + (ZArith.BinInt.Z.rem n d))%Z).

Axiom cmod_remainder :
  forall (n:Numbers.BinNums.Z) (d:Numbers.BinNums.Z),
  ((0%Z <= n)%Z -> (0%Z < d)%Z ->
   (0%Z <= (ZArith.BinInt.Z.rem n d))%Z /\ ((ZArith.BinInt.Z.rem n d) < d)%Z) /\
  ((n <= 0%Z)%Z -> (0%Z < d)%Z ->
   ((-d)%Z < (ZArith.BinInt.Z.rem n d))%Z /\
   ((ZArith.BinInt.Z.rem n d) <= 0%Z)%Z) /\
  ((0%Z <= n)%Z -> (d < 0%Z)%Z ->
   (0%Z <= (ZArith.BinInt.Z.rem n d))%Z /\
   ((ZArith.BinInt.Z.rem n d) < (-d)%Z)%Z) /\
  ((n <= 0%Z)%Z -> (d < 0%Z)%Z ->
   (d < (ZArith.BinInt.Z.rem n d))%Z /\ ((ZArith.BinInt.Z.rem n d) <= 0%Z)%Z).

Axiom cdiv_neutral :
  forall (a:Numbers.BinNums.Z), ((ZArith.BinInt.Z.quot a 1%Z) = a).

Axiom cdiv_inv :
  forall (a:Numbers.BinNums.Z), ~ (a = 0%Z) ->
  ((ZArith.BinInt.Z.quot a a) = 1%Z).

Axiom cdiv_closed_remainder :
  forall (a:Numbers.BinNums.Z) (b:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  (0%Z <= a)%Z -> (0%Z <= b)%Z ->
  (0%Z <= (b - a)%Z)%Z /\ ((b - a)%Z < n)%Z ->
  ((ZArith.BinInt.Z.rem a n) = (ZArith.BinInt.Z.rem b n)) -> (a = b).

(* Why3 assumption *)
Inductive addr :=
  | addr'mk : Numbers.BinNums.Z -> Numbers.BinNums.Z -> addr.
Axiom addr_WhyType : WhyType addr.
Existing Instance addr_WhyType.

(* Why3 assumption *)
Definition base (v:addr) : Numbers.BinNums.Z :=
  match v with
  | addr'mk x x1 => x
  end.

(* Why3 assumption *)
Definition offset (v:addr) : Numbers.BinNums.Z :=
  match v with
  | addr'mk x x1 => x1
  end.

(* Why3 assumption *)
Definition malloc := Numbers.BinNums.Z -> Numbers.BinNums.Z.

(* Why3 assumption *)
Definition null : addr := addr'mk 0%Z 0%Z.

(* Why3 assumption *)
Definition global (b:Numbers.BinNums.Z) : addr := addr'mk b 0%Z.

Parameter addr_le: addr -> addr -> Prop.

Parameter addr_lt: addr -> addr -> Prop.

Parameter addr_le_bool: addr -> addr -> Init.Datatypes.bool.

Parameter addr_lt_bool: addr -> addr -> Init.Datatypes.bool.

Axiom addr_le_def :
  forall (p:addr) (q:addr), ((base p) = (base q)) ->
  addr_le p q <-> ((offset p) <= (offset q))%Z.

Axiom addr_lt_def :
  forall (p:addr) (q:addr), ((base p) = (base q)) ->
  addr_lt p q <-> ((offset p) < (offset q))%Z.

Axiom addr_le_bool_def :
  forall (p:addr) (q:addr),
  addr_le p q <-> ((addr_le_bool p q) = Init.Datatypes.true).

Axiom addr_lt_bool_def :
  forall (p:addr) (q:addr),
  addr_lt p q <-> ((addr_lt_bool p q) = Init.Datatypes.true).

(* Why3 assumption *)
Definition shift (p:addr) (k:Numbers.BinNums.Z) : addr :=
  addr'mk (base p) ((offset p) + k)%Z.

(* Why3 assumption *)
Definition valid_rw (m:Numbers.BinNums.Z -> Numbers.BinNums.Z) (p:addr)
    (n:Numbers.BinNums.Z) : Prop :=
  (0%Z < n)%Z ->
  (0%Z < (base p))%Z /\
  (0%Z <= (offset p))%Z /\ (((offset p) + n)%Z <= (m (base p)))%Z.

(* Why3 assumption *)
Definition valid_rd (m:Numbers.BinNums.Z -> Numbers.BinNums.Z) (p:addr)
    (n:Numbers.BinNums.Z) : Prop :=
  (0%Z < n)%Z ->
  ~ (0%Z = (base p)) /\
  (0%Z <= (offset p))%Z /\ (((offset p) + n)%Z <= (m (base p)))%Z.

(* Why3 assumption *)
Definition valid_obj (m:Numbers.BinNums.Z -> Numbers.BinNums.Z) (p:addr) :
    Prop :=
  (p = null) \/
  ~ (0%Z = (base p)) /\
  (0%Z <= (offset p))%Z /\
  ((offset p) <= (m (base p)))%Z /\ (0%Z < (m (base p)))%Z.

(* Why3 assumption *)
Definition invalid (m:Numbers.BinNums.Z -> Numbers.BinNums.Z) (p:addr)
    (n:Numbers.BinNums.Z) : Prop :=
  (n <= 0%Z)%Z \/
  ((base p) = 0%Z) \/
  ((m (base p)) <= (offset p))%Z \/ (((offset p) + n)%Z <= 0%Z)%Z.

Axiom valid_rw_rd :
  forall (m:Numbers.BinNums.Z -> Numbers.BinNums.Z), forall (p:addr),
  forall (n:Numbers.BinNums.Z), valid_rw m p n -> valid_rd m p n.

Axiom valid_string :
  forall (m:Numbers.BinNums.Z -> Numbers.BinNums.Z), forall (p:addr),
  ((base p) < 0%Z)%Z ->
  (0%Z <= (offset p))%Z /\ ((offset p) < (m (base p)))%Z ->
  valid_rd m p 1%Z /\ ~ valid_rw m p 1%Z.

(* Why3 assumption *)
Definition included (p:addr) (lp:Numbers.BinNums.Z) (q:addr)
    (lq:Numbers.BinNums.Z) : Prop :=
  (0%Z < lp)%Z ->
  (0%Z <= lq)%Z /\
  ((base p) = (base q)) /\
  ((offset q) <= (offset p))%Z /\
  (((offset p) + lp)%Z <= ((offset q) + lq)%Z)%Z.

(* Why3 assumption *)
Definition separated (p:addr) (lp:Numbers.BinNums.Z) (q:addr)
    (lq:Numbers.BinNums.Z) : Prop :=
  (lp <= 0%Z)%Z \/
  (lq <= 0%Z)%Z \/
  ~ ((base p) = (base q)) \/
  (((offset q) + lq)%Z <= (offset p))%Z \/
  (((offset p) + lp)%Z <= (offset q))%Z.

Axiom separated_1 :
  forall (p:addr) (q:addr),
  forall (lp:Numbers.BinNums.Z) (lq:Numbers.BinNums.Z) (i:Numbers.BinNums.Z)
    (j:Numbers.BinNums.Z),
  separated p lp q lq ->
  ((offset p) <= i)%Z /\ (i < ((offset p) + lp)%Z)%Z ->
  ((offset q) <= j)%Z /\ (j < ((offset q) + lq)%Z)%Z ->
  ~ ((addr'mk (base p) i) = (addr'mk (base q) j)).

Axiom separated_included :
  forall (p:addr) (q:addr),
  forall (lp:Numbers.BinNums.Z) (lq:Numbers.BinNums.Z), (0%Z < lp)%Z ->
  (0%Z < lq)%Z -> separated p lp q lq -> ~ included p lp q lq.

Axiom included_trans :
  forall (p:addr) (q:addr) (r:addr),
  forall (lp:Numbers.BinNums.Z) (lq:Numbers.BinNums.Z) (lr:Numbers.BinNums.Z),
  included p lp q lq -> included q lq r lr -> included p lp r lr.

Axiom separated_trans :
  forall (p:addr) (q:addr) (r:addr),
  forall (lp:Numbers.BinNums.Z) (lq:Numbers.BinNums.Z) (lr:Numbers.BinNums.Z),
  included p lp q lq -> separated q lq r lr -> separated p lp r lr.

Axiom separated_sym :
  forall (p:addr) (q:addr),
  forall (lp:Numbers.BinNums.Z) (lq:Numbers.BinNums.Z),
  separated p lp q lq <-> separated q lq p lp.

Parameter region: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Parameter linked: (Numbers.BinNums.Z -> Numbers.BinNums.Z) -> Prop.

Parameter static_malloc: Numbers.BinNums.Z -> Numbers.BinNums.Z.

(* Why3 assumption *)
Definition statically_allocated (base1:Numbers.BinNums.Z) : Prop :=
  (base1 = 0%Z) \/ (0%Z < (static_malloc base1))%Z.

Axiom valid_pointers_are_statically_allocated :
  forall (a:addr) (m:Numbers.BinNums.Z -> Numbers.BinNums.Z)
    (n:Numbers.BinNums.Z),
  (0%Z < n)%Z -> valid_rd m a n -> statically_allocated (base a).

Parameter int_of_addr: addr -> Numbers.BinNums.Z.

Parameter addr_of_int: Numbers.BinNums.Z -> addr.

Axiom addr_of_null : ((int_of_addr null) = 0%Z).

Axiom addr_of_int_bijection :
  forall (p:addr), statically_allocated (base p) ->
  ((addr_of_int (int_of_addr p)) = p).

Axiom table : Type.
Parameter table_WhyType : WhyType table.
Existing Instance table_WhyType.

Parameter table_of_base: Numbers.BinNums.Z -> table.

Parameter table_to_offset: table -> Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom table_to_offset_zero :
  forall (t:table), ((table_to_offset t 0%Z) = 0%Z).

Axiom table_to_offset_monotonic :
  forall (t:table), forall (o1:Numbers.BinNums.Z) (o2:Numbers.BinNums.Z),
  (o1 <= o2)%Z <-> ((table_to_offset t o1) <= (table_to_offset t o2))%Z.

(* Why3 assumption *)
Definition is_bool (x:Numbers.BinNums.Z) : Prop := (x = 0%Z) \/ (x = 1%Z).

(* Why3 assumption *)
Definition is_uint8 (x:Numbers.BinNums.Z) : Prop :=
  (0%Z <= x)%Z /\ (x < 256%Z)%Z.

(* Why3 assumption *)
Definition is_sint8 (x:Numbers.BinNums.Z) : Prop :=
  ((-128%Z)%Z <= x)%Z /\ (x < 128%Z)%Z.

(* Why3 assumption *)
Definition is_uint16 (x:Numbers.BinNums.Z) : Prop :=
  (0%Z <= x)%Z /\ (x < 65536%Z)%Z.

(* Why3 assumption *)
Definition is_sint16 (x:Numbers.BinNums.Z) : Prop :=
  ((-32768%Z)%Z <= x)%Z /\ (x < 32768%Z)%Z.

(* Why3 assumption *)
Definition is_uint32 (x:Numbers.BinNums.Z) : Prop :=
  (0%Z <= x)%Z /\ (x < 4294967296%Z)%Z.

(* Why3 assumption *)
Definition is_sint32 (x:Numbers.BinNums.Z) : Prop :=
  ((-2147483648%Z)%Z <= x)%Z /\ (x < 2147483648%Z)%Z.

(* Why3 assumption *)
Definition is_uint64 (x:Numbers.BinNums.Z) : Prop :=
  (0%Z <= x)%Z /\ (x < 18446744073709551616%Z)%Z.

(* Why3 assumption *)
Definition is_sint64 (x:Numbers.BinNums.Z) : Prop :=
  ((-9223372036854775808%Z)%Z <= x)%Z /\ (x < 9223372036854775808%Z)%Z.

Axiom is_bool0 : is_bool 0%Z.

Axiom is_bool1 : is_bool 1%Z.

Parameter to_bool: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom to_bool'def :
  forall (x:Numbers.BinNums.Z),
  ((x = 0%Z) -> ((to_bool x) = 0%Z)) /\ (~ (x = 0%Z) -> ((to_bool x) = 1%Z)).

Parameter to_uint8: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom to_uint8'def :
  forall (x:Numbers.BinNums.Z),
  ((x < 0%Z)%Z -> ((to_uint8 x) = (to_uint8 (x + 256%Z)%Z))) /\
  (~ (x < 0%Z)%Z ->
   ((256%Z <= x)%Z -> ((to_uint8 x) = (to_uint8 (x - 256%Z)%Z))) /\
   (~ (256%Z <= x)%Z -> ((to_uint8 x) = x))).

Parameter to_sint8: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom to_sint8'def :
  forall (x:Numbers.BinNums.Z),
  ((x < (-128%Z)%Z)%Z -> ((to_sint8 x) = (to_sint8 (x + 256%Z)%Z))) /\
  (~ (x < (-128%Z)%Z)%Z ->
   ((128%Z <= x)%Z -> ((to_sint8 x) = (to_sint8 (x - 256%Z)%Z))) /\
   (~ (128%Z <= x)%Z -> ((to_sint8 x) = x))).

Parameter to_uint16: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom to_uint16'def :
  forall (x:Numbers.BinNums.Z),
  ((x < 0%Z)%Z -> ((to_uint16 x) = (to_uint16 (x + 65536%Z)%Z))) /\
  (~ (x < 0%Z)%Z ->
   ((65536%Z <= x)%Z -> ((to_uint16 x) = (to_uint16 (x - 65536%Z)%Z))) /\
   (~ (65536%Z <= x)%Z -> ((to_uint16 x) = x))).

Parameter to_sint16: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom to_sint16'def :
  forall (x:Numbers.BinNums.Z),
  ((x < (-32768%Z)%Z)%Z -> ((to_sint16 x) = (to_sint16 (x + 65536%Z)%Z))) /\
  (~ (x < (-32768%Z)%Z)%Z ->
   ((32768%Z <= x)%Z -> ((to_sint16 x) = (to_sint16 (x - 65536%Z)%Z))) /\
   (~ (32768%Z <= x)%Z -> ((to_sint16 x) = x))).

Parameter to_uint32: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom to_uint32'def :
  forall (x:Numbers.BinNums.Z),
  ((x < 0%Z)%Z -> ((to_uint32 x) = (to_uint32 (x + 4294967296%Z)%Z))) /\
  (~ (x < 0%Z)%Z ->
   ((4294967296%Z <= x)%Z ->
    ((to_uint32 x) = (to_uint32 (x - 4294967296%Z)%Z))) /\
   (~ (4294967296%Z <= x)%Z -> ((to_uint32 x) = x))).

Parameter to_sint32: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom to_sint32'def :
  forall (x:Numbers.BinNums.Z),
  ((x < (-2147483648%Z)%Z)%Z ->
   ((to_sint32 x) = (to_sint32 (x + 4294967296%Z)%Z))) /\
  (~ (x < (-2147483648%Z)%Z)%Z ->
   ((2147483648%Z <= x)%Z ->
    ((to_sint32 x) = (to_sint32 (x - 4294967296%Z)%Z))) /\
   (~ (2147483648%Z <= x)%Z -> ((to_sint32 x) = x))).

Parameter to_uint64: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom to_uint64'def :
  forall (x:Numbers.BinNums.Z),
  ((x < 0%Z)%Z ->
   ((to_uint64 x) = (to_uint64 (x + 18446744073709551616%Z)%Z))) /\
  (~ (x < 0%Z)%Z ->
   ((18446744073709551616%Z <= x)%Z ->
    ((to_uint64 x) = (to_uint64 (x - 18446744073709551616%Z)%Z))) /\
   (~ (18446744073709551616%Z <= x)%Z -> ((to_uint64 x) = x))).

Parameter to_sint64: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom to_sint64'def :
  forall (x:Numbers.BinNums.Z),
  ((x < (-9223372036854775808%Z)%Z)%Z ->
   ((to_sint64 x) = (to_sint64 (x + 18446744073709551616%Z)%Z))) /\
  (~ (x < (-9223372036854775808%Z)%Z)%Z ->
   ((9223372036854775808%Z <= x)%Z ->
    ((to_sint64 x) = (to_sint64 (x - 18446744073709551616%Z)%Z))) /\
   (~ (9223372036854775808%Z <= x)%Z -> ((to_sint64 x) = x))).

Parameter two_power_abs: Numbers.BinNums.Z -> Numbers.BinNums.Z.

(* Why3 assumption *)
Definition is_uint (n:Numbers.BinNums.Z) (x:Numbers.BinNums.Z) : Prop :=
  (0%Z <= x)%Z /\ (x < (two_power_abs n))%Z.

(* Why3 assumption *)
Definition is_sint (n:Numbers.BinNums.Z) (x:Numbers.BinNums.Z) : Prop :=
  ((-(two_power_abs n))%Z <= x)%Z /\ (x < (two_power_abs n))%Z.

Parameter to_uint:
  Numbers.BinNums.Z -> Numbers.BinNums.Z -> Numbers.BinNums.Z.

Parameter to_sint:
  Numbers.BinNums.Z -> Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom is_to_uint8 : forall (x:Numbers.BinNums.Z), is_uint8 (to_uint8 x).

Axiom is_to_sint8 : forall (x:Numbers.BinNums.Z), is_sint8 (to_sint8 x).

Axiom is_to_uint16 : forall (x:Numbers.BinNums.Z), is_uint16 (to_uint16 x).

Axiom is_to_sint16 : forall (x:Numbers.BinNums.Z), is_sint16 (to_sint16 x).

Axiom is_to_uint32 : forall (x:Numbers.BinNums.Z), is_uint32 (to_uint32 x).

Axiom is_to_sint32 : forall (x:Numbers.BinNums.Z), is_sint32 (to_sint32 x).

Axiom is_to_uint64 : forall (x:Numbers.BinNums.Z), is_uint64 (to_uint64 x).

Axiom is_to_sint64 : forall (x:Numbers.BinNums.Z), is_sint64 (to_sint64 x).

Axiom id_uint8 :
  forall (x:Numbers.BinNums.Z), is_uint8 x -> ((to_uint8 x) = x).

Axiom id_sint8 :
  forall (x:Numbers.BinNums.Z), is_sint8 x -> ((to_sint8 x) = x).

Axiom id_uint16 :
  forall (x:Numbers.BinNums.Z), is_uint16 x -> ((to_uint16 x) = x).

Axiom id_sint16 :
  forall (x:Numbers.BinNums.Z), is_sint16 x -> ((to_sint16 x) = x).

Axiom id_uint32 :
  forall (x:Numbers.BinNums.Z), is_uint32 x -> ((to_uint32 x) = x).

Axiom id_sint32 :
  forall (x:Numbers.BinNums.Z), is_sint32 x -> ((to_sint32 x) = x).

Axiom id_uint64 :
  forall (x:Numbers.BinNums.Z), is_uint64 x -> ((to_uint64 x) = x).

Axiom id_sint64 :
  forall (x:Numbers.BinNums.Z), is_sint64 x -> ((to_sint64 x) = x).

Axiom id_uint8_inl :
  forall (x:Numbers.BinNums.Z), (0%Z <= x)%Z /\ (x < 256%Z)%Z ->
  ((to_uint8 x) = x).

Axiom id_sint8_inl :
  forall (x:Numbers.BinNums.Z), ((-128%Z)%Z <= x)%Z /\ (x < 128%Z)%Z ->
  ((to_sint8 x) = x).

Axiom id_uint16_inl :
  forall (x:Numbers.BinNums.Z), (0%Z <= x)%Z /\ (x < 65536%Z)%Z ->
  ((to_uint16 x) = x).

Axiom id_sint16_inl :
  forall (x:Numbers.BinNums.Z), ((-32768%Z)%Z <= x)%Z /\ (x < 32768%Z)%Z ->
  ((to_sint16 x) = x).

Axiom id_uint32_inl :
  forall (x:Numbers.BinNums.Z), (0%Z <= x)%Z /\ (x < 4294967296%Z)%Z ->
  ((to_uint32 x) = x).

Axiom id_sint32_inl :
  forall (x:Numbers.BinNums.Z),
  ((-2147483648%Z)%Z <= x)%Z /\ (x < 2147483648%Z)%Z -> ((to_sint32 x) = x).

Axiom id_uint64_inl :
  forall (x:Numbers.BinNums.Z),
  (0%Z <= x)%Z /\ (x < 18446744073709551616%Z)%Z -> ((to_uint64 x) = x).

Axiom id_sint64_inl :
  forall (x:Numbers.BinNums.Z),
  ((-9223372036854775808%Z)%Z <= x)%Z /\ (x < 9223372036854775808%Z)%Z ->
  ((to_sint64 x) = x).

Axiom proj_int8 :
  forall (x:Numbers.BinNums.Z), ((to_sint8 (to_uint8 x)) = (to_sint8 x)).

Axiom proj_int16 :
  forall (x:Numbers.BinNums.Z), ((to_sint16 (to_uint16 x)) = (to_sint16 x)).

Axiom proj_int32 :
  forall (x:Numbers.BinNums.Z), ((to_sint32 (to_uint32 x)) = (to_sint32 x)).

Axiom proj_int64 :
  forall (x:Numbers.BinNums.Z), ((to_sint64 (to_uint64 x)) = (to_sint64 x)).

Parameter bit_testb:
  Numbers.BinNums.Z -> Numbers.BinNums.Z -> Init.Datatypes.bool.

Parameter bit_test: Numbers.BinNums.Z -> Numbers.BinNums.Z -> Prop.

(* Why3 assumption *)
Definition lnot (x:Numbers.BinNums.Z) : Numbers.BinNums.Z :=
  ((-x)%Z - 1%Z)%Z.

Parameter land: Numbers.BinNums.Z -> Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom Assoc :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z) (z:Numbers.BinNums.Z),
  ((land (land x y) z) = (land x (land y z))).

Axiom Comm :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z),
  ((land x y) = (land y x)).

Parameter lxor: Numbers.BinNums.Z -> Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom Assoc1 :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z) (z:Numbers.BinNums.Z),
  ((lxor (lxor x y) z) = (lxor x (lxor y z))).

Axiom Comm1 :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z),
  ((lxor x y) = (lxor y x)).

Parameter lor: Numbers.BinNums.Z -> Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom Assoc2 :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z) (z:Numbers.BinNums.Z),
  ((lor (lor x y) z) = (lor x (lor y z))).

Axiom Comm2 :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), ((lor x y) = (lor y x)).

Parameter lsl: Numbers.BinNums.Z -> Numbers.BinNums.Z -> Numbers.BinNums.Z.

Parameter lsr: Numbers.BinNums.Z -> Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom land_idemp : forall (x:Numbers.BinNums.Z), ((land x x) = x).

Axiom land_idemp_bis :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z),
  ((land x (land x y)) = (land x y)).

Axiom land_0 : forall (x:Numbers.BinNums.Z), ((land 0%Z x) = 0%Z).

Axiom land_0bis : forall (x:Numbers.BinNums.Z), ((land x 0%Z) = 0%Z).

Axiom land_1 : forall (x:Numbers.BinNums.Z), ((land (-1%Z)%Z x) = x).

Axiom land_1bis : forall (x:Numbers.BinNums.Z), ((land x (-1%Z)%Z) = x).

Axiom lor_idemp : forall (x:Numbers.BinNums.Z), ((lor x x) = x).

Axiom lor_idemp_bis :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z),
  ((lor x (lor x y)) = (lor x y)).

Axiom lor_1 : forall (x:Numbers.BinNums.Z), ((lor (-1%Z)%Z x) = (-1%Z)%Z).

Axiom lor_1bis : forall (x:Numbers.BinNums.Z), ((lor x (-1%Z)%Z) = (-1%Z)%Z).

Axiom lor_0 : forall (x:Numbers.BinNums.Z), ((lor 0%Z x) = x).

Axiom lor_0bis : forall (x:Numbers.BinNums.Z), ((lor x 0%Z) = x).

Axiom lxor_nilpotent : forall (x:Numbers.BinNums.Z), ((lxor x x) = 0%Z).

Axiom lxor_nilpotent_bis :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z),
  ((lxor x (lxor x y)) = y).

Axiom lxor_1 : forall (x:Numbers.BinNums.Z), ((lxor (-1%Z)%Z x) = (lnot x)).

Axiom lxor_1bis :
  forall (x:Numbers.BinNums.Z), ((lxor x (-1%Z)%Z) = (lnot x)).

Axiom lxor_0 : forall (x:Numbers.BinNums.Z), ((lxor 0%Z x) = x).

Axiom lxor_0bis : forall (x:Numbers.BinNums.Z), ((lxor x 0%Z) = x).

Axiom lsl_0 : forall (x:Numbers.BinNums.Z), ((lsl x 0%Z) = x).

Axiom lsl_1 : forall (x:Numbers.BinNums.Z), ((lsl x 1%Z) = (2%Z * x)%Z).

Axiom lsl_add :
  forall (x:Numbers.BinNums.Z) (p:Numbers.BinNums.Z) (q:Numbers.BinNums.Z),
  (0%Z <= p)%Z -> (0%Z <= q)%Z -> ((lsl (lsl x p) q) = (lsl x (p + q)%Z)).

Axiom lsr_0 : forall (x:Numbers.BinNums.Z), ((lsr x 0%Z) = x).

Axiom lsr_1 :
  forall (x:Numbers.BinNums.Z), (0%Z <= x)%Z ->
  ((lsr x 1%Z) = (ZArith.BinInt.Z.quot x 2%Z)).

Axiom lsr_add :
  forall (x:Numbers.BinNums.Z) (p:Numbers.BinNums.Z) (q:Numbers.BinNums.Z),
  (0%Z <= p)%Z -> (0%Z <= q)%Z -> ((lsr (lsr x p) q) = (lsr x (p + q)%Z)).

Axiom lsl_lsr_add :
  forall (x:Numbers.BinNums.Z) (p:Numbers.BinNums.Z) (q:Numbers.BinNums.Z),
  (0%Z <= q)%Z /\ (q <= p)%Z -> ((lsr (lsl x p) q) = (lsl x (p - q)%Z)).

Axiom bit_test_def :
  forall (x:Numbers.BinNums.Z) (k:Numbers.BinNums.Z),
  ((bit_testb x k) = Init.Datatypes.true) <-> bit_test x k.

Axiom bit_test_extraction :
  forall (x:Numbers.BinNums.Z) (k:Numbers.BinNums.Z), (0%Z <= k)%Z ->
  ~ ((land x (lsl 1%Z k)) = 0%Z) <-> bit_test x k.

Axiom lsl_1_0 : ((lsl 1%Z 0%Z) = 1%Z).

Axiom bit_test_extraction_bis :
  forall (x:Numbers.BinNums.Z), ~ ((land 1%Z x) = 0%Z) -> bit_test x 0%Z.

Axiom bit_test_extraction_bis_eq :
  forall (x:Numbers.BinNums.Z), bit_test x 0%Z -> ((land 1%Z x) = 1%Z).

Axiom lnot_extraction :
  forall (x:Numbers.BinNums.Z) (i:Numbers.BinNums.Z), (0%Z <= i)%Z ->
  bit_test (lnot x) i <-> ~ bit_test x i.

Axiom land_extraction :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z) (i:Numbers.BinNums.Z),
  (0%Z <= i)%Z -> bit_test (land x y) i <-> bit_test x i /\ bit_test y i.

Axiom lor_extraction :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z) (i:Numbers.BinNums.Z),
  (0%Z <= i)%Z -> bit_test (lor x y) i <-> bit_test x i \/ bit_test y i.

Axiom lxor_extraction :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z) (i:Numbers.BinNums.Z),
  (0%Z <= i)%Z -> bit_test (lxor x y) i <-> (bit_test x i <-> ~ bit_test y i).

Axiom land_1_lsl_1 :
  forall (a:Numbers.BinNums.Z) (x:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  (0%Z <= n)%Z -> (a < (lsl 1%Z n))%Z ->
  (((2%Z * a)%Z + (land 1%Z x))%Z < (lsl 1%Z (1%Z + n)%Z))%Z.

Axiom lsl_extraction_sup :
  forall (x:Numbers.BinNums.Z) (n:Numbers.BinNums.Z) (m:Numbers.BinNums.Z),
  (0%Z <= n)%Z -> (0%Z <= m)%Z -> (n <= m)%Z ->
  bit_test (lsl x n) m <-> bit_test x (m - n)%Z.

Axiom lsl_extraction_inf :
  forall (x:Numbers.BinNums.Z) (n:Numbers.BinNums.Z) (m:Numbers.BinNums.Z),
  (0%Z <= n)%Z -> (0%Z <= m)%Z -> (m < n)%Z -> ~ bit_test (lsl x n) m.

Axiom lsr_extractionl :
  forall (x:Numbers.BinNums.Z) (n:Numbers.BinNums.Z) (m:Numbers.BinNums.Z),
  (0%Z <= n)%Z -> (0%Z <= m)%Z ->
  bit_test (lsr x n) m <-> bit_test x (m + n)%Z.

Axiom lsl1_extraction :
  forall (i:Numbers.BinNums.Z) (j:Numbers.BinNums.Z), (0%Z <= i)%Z ->
  (0%Z <= j)%Z -> bit_test (lsl 1%Z i) j <-> (i = j).

Axiom to_uint8_extraction_sup :
  forall (x:Numbers.BinNums.Z) (i:Numbers.BinNums.Z), (8%Z <= i)%Z ->
  is_uint8 x -> ~ bit_test x i.

Axiom to_uint8_extraction_inf :
  forall (x:Numbers.BinNums.Z) (i:Numbers.BinNums.Z),
  (0%Z <= i)%Z /\ (i < 8%Z)%Z -> bit_test (to_uint8 x) i <-> bit_test x i.

Axiom to_uint16_extraction_sup :
  forall (x:Numbers.BinNums.Z) (i:Numbers.BinNums.Z), (16%Z <= i)%Z ->
  is_uint16 x -> ~ bit_test x i.

Axiom to_uint16_extraction_inf :
  forall (x:Numbers.BinNums.Z) (i:Numbers.BinNums.Z),
  (0%Z <= i)%Z /\ (i < 16%Z)%Z -> bit_test (to_uint16 x) i <-> bit_test x i.

Axiom to_uint32_extraction_sup :
  forall (x:Numbers.BinNums.Z) (i:Numbers.BinNums.Z), (32%Z <= i)%Z ->
  is_uint32 x -> ~ bit_test x i.

Axiom to_uint32_extraction_inf :
  forall (x:Numbers.BinNums.Z) (i:Numbers.BinNums.Z),
  (0%Z <= i)%Z /\ (i < 32%Z)%Z -> bit_test (to_uint32 x) i <-> bit_test x i.

Axiom to_uint64_extraction_sup :
  forall (x:Numbers.BinNums.Z) (i:Numbers.BinNums.Z), (64%Z <= i)%Z ->
  is_uint64 x -> ~ bit_test x i.

Axiom to_uint64_extraction_inf :
  forall (x:Numbers.BinNums.Z) (i:Numbers.BinNums.Z),
  (0%Z <= i)%Z /\ (i < 64%Z)%Z -> bit_test (to_uint64 x) i <-> bit_test x i.

Axiom to_sint8_extraction_sup :
  forall (x:Numbers.BinNums.Z) (i:Numbers.BinNums.Z), (7%Z <= i)%Z ->
  is_sint8 x -> bit_test x i <-> (x < 0%Z)%Z.

Axiom to_sint8_extraction_inf :
  forall (x:Numbers.BinNums.Z) (i:Numbers.BinNums.Z),
  (0%Z <= i)%Z /\ (i < 7%Z)%Z -> bit_test (to_sint8 x) i <-> bit_test x i.

Axiom to_sint16_extraction_sup :
  forall (x:Numbers.BinNums.Z) (i:Numbers.BinNums.Z), (15%Z <= i)%Z ->
  is_sint16 x -> bit_test x i <-> (x < 0%Z)%Z.

Axiom to_sint16_extraction_inf :
  forall (x:Numbers.BinNums.Z) (i:Numbers.BinNums.Z),
  (0%Z <= i)%Z /\ (i < 15%Z)%Z -> bit_test (to_sint16 x) i <-> bit_test x i.

Axiom to_sint32_extraction_sup :
  forall (x:Numbers.BinNums.Z) (i:Numbers.BinNums.Z), (31%Z <= i)%Z ->
  is_sint32 x -> bit_test x i <-> (x < 0%Z)%Z.

Axiom to_sint32_extraction_inf :
  forall (x:Numbers.BinNums.Z) (i:Numbers.BinNums.Z),
  (0%Z <= i)%Z /\ (i < 31%Z)%Z -> bit_test (to_sint32 x) i <-> bit_test x i.

Axiom to_sint64_extraction_sup :
  forall (x:Numbers.BinNums.Z) (i:Numbers.BinNums.Z), (63%Z <= i)%Z ->
  is_sint64 x -> bit_test x i <-> (x < 0%Z)%Z.

Axiom to_sint64_extraction_inf :
  forall (x:Numbers.BinNums.Z) (i:Numbers.BinNums.Z),
  (0%Z <= i)%Z /\ (i < 63%Z)%Z -> bit_test (to_sint64 x) i <-> bit_test x i.

Axiom is_uint_lxor :
  forall (n:Numbers.BinNums.Z) (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z),
  is_uint n x -> is_uint n y -> ((to_uint n (lxor x y)) = (lxor x y)).

Axiom is_uint8_lxor :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), is_uint8 x ->
  is_uint8 y -> ((to_uint8 (lxor x y)) = (lxor x y)).

Axiom is_uint8_lor :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), is_uint8 x ->
  is_uint8 y -> ((to_uint8 (lor x y)) = (lor x y)).

Axiom is_uint8_land :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), is_uint8 x ->
  is_uint8 y -> ((to_uint8 (land x y)) = (land x y)).

Axiom is_uint8_lsr :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), (0%Z <= y)%Z ->
  is_uint8 x -> ((to_uint8 (lsr x y)) = (lsr x y)).

Axiom is_uint8_lsl1_inf :
  forall (y:Numbers.BinNums.Z), (0%Z <= y)%Z /\ (y < 8%Z)%Z ->
  ((to_uint8 (lsl 1%Z y)) = (lsl 1%Z y)).

Axiom is_uint8_lsl1_sup :
  forall (y:Numbers.BinNums.Z), (8%Z <= y)%Z ->
  ((to_uint8 (lsl 1%Z y)) = 0%Z).

Axiom is_uint16_lxor :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), is_uint16 x ->
  is_uint16 y -> ((to_uint16 (lxor x y)) = (lxor x y)).

Axiom is_uint16_lor :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), is_uint16 x ->
  is_uint16 y -> ((to_uint16 (lor x y)) = (lor x y)).

Axiom is_uint16_land :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), is_uint16 x ->
  is_uint16 y -> ((to_uint16 (land x y)) = (land x y)).

Axiom is_uint16_lsr :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), (0%Z <= y)%Z ->
  is_uint16 x -> ((to_uint16 (lsr x y)) = (lsr x y)).

Axiom is_uint16_lsl1_inf :
  forall (y:Numbers.BinNums.Z), (0%Z <= y)%Z /\ (y < 16%Z)%Z ->
  ((to_uint16 (lsl 1%Z y)) = (lsl 1%Z y)).

Axiom is_uint16_lsl1_sup :
  forall (y:Numbers.BinNums.Z), (16%Z <= y)%Z ->
  ((to_uint16 (lsl 1%Z y)) = 0%Z).

Axiom is_uint32_lxor :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), is_uint32 x ->
  is_uint32 y -> ((to_uint32 (lxor x y)) = (lxor x y)).

Axiom is_uint32_lor :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), is_uint32 x ->
  is_uint32 y -> ((to_uint32 (lor x y)) = (lor x y)).

Axiom is_uint32_land :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), is_uint32 x ->
  is_uint32 y -> ((to_uint32 (land x y)) = (land x y)).

Axiom is_uint32_lsr :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), (0%Z <= y)%Z ->
  is_uint32 x -> ((to_uint32 (lsr x y)) = (lsr x y)).

Axiom is_uint32_lsl1_inf :
  forall (y:Numbers.BinNums.Z), (0%Z <= y)%Z /\ (y < 32%Z)%Z ->
  ((to_uint32 (lsl 1%Z y)) = (lsl 1%Z y)).

Axiom is_uint32_lsl1_sup :
  forall (y:Numbers.BinNums.Z), (32%Z <= y)%Z ->
  ((to_uint32 (lsl 1%Z y)) = 0%Z).

Axiom is_uint64_lxor :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), is_uint64 x ->
  is_uint64 y -> ((to_uint64 (lxor x y)) = (lxor x y)).

Axiom is_uint64_lor :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), is_uint64 x ->
  is_uint64 y -> ((to_uint64 (lor x y)) = (lor x y)).

Axiom is_uint64_land :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), is_uint64 x ->
  is_uint64 y -> ((to_uint64 (land x y)) = (land x y)).

Axiom is_uint64_lsr :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), (0%Z <= y)%Z ->
  is_uint64 x -> ((to_uint64 (lsr x y)) = (lsr x y)).

Axiom is_uint64_lsl1_inf :
  forall (y:Numbers.BinNums.Z), (0%Z <= y)%Z /\ (y < 64%Z)%Z ->
  ((to_uint64 (lsl 1%Z y)) = (lsl 1%Z y)).

Axiom is_uint64_lsl1_sup :
  forall (y:Numbers.BinNums.Z), (64%Z <= y)%Z ->
  ((to_uint64 (lsl 1%Z y)) = 0%Z).

Axiom is_sint8_lnot :
  forall (x:Numbers.BinNums.Z), is_sint8 x ->
  ((to_sint8 (lnot x)) = (lnot x)).

Axiom is_sint8_lxor :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), is_sint8 x ->
  is_sint8 y -> ((to_sint8 (lxor x y)) = (lxor x y)).

Axiom is_sint8_lor :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), is_sint8 x ->
  is_sint8 y -> ((to_sint8 (lor x y)) = (lor x y)).

Axiom is_sint8_land :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), is_sint8 x ->
  is_sint8 y -> ((to_sint8 (land x y)) = (land x y)).

Axiom is_sint8_lsr :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), (0%Z <= y)%Z ->
  is_sint8 x -> ((to_sint8 (lsr x y)) = (lsr x y)).

Axiom is_sint8_lsl1 : ((lsl 1%Z 7%Z) = 128%Z).

Axiom is_sint8_lsl1_inf :
  forall (y:Numbers.BinNums.Z), (0%Z <= y)%Z /\ (y < 7%Z)%Z ->
  ((to_sint8 (lsl 1%Z y)) = (lsl 1%Z y)).

Axiom is_sint8_lsl1_sup :
  forall (y:Numbers.BinNums.Z), (8%Z <= y)%Z ->
  ((to_sint8 (lsl 1%Z y)) = 0%Z).

Axiom is_sint16_lnot :
  forall (x:Numbers.BinNums.Z), is_sint16 x ->
  ((to_sint16 (lnot x)) = (lnot x)).

Axiom is_sint16_lxor :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), is_sint16 x ->
  is_sint16 y -> ((to_sint16 (lxor x y)) = (lxor x y)).

Axiom is_sint16_lor :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), is_sint16 x ->
  is_sint16 y -> ((to_sint16 (lor x y)) = (lor x y)).

Axiom is_sint16_land :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), is_sint16 x ->
  is_sint16 y -> ((to_sint16 (land x y)) = (land x y)).

Axiom is_sint16_lsr :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), (0%Z <= y)%Z ->
  is_sint16 x -> ((to_sint16 (lsr x y)) = (lsr x y)).

Axiom is_sint16_lsl1 : ((lsl 1%Z 15%Z) = 32768%Z).

Axiom is_sint16_lsl1_inf :
  forall (y:Numbers.BinNums.Z), (0%Z <= y)%Z /\ (y < 15%Z)%Z ->
  ((to_sint16 (lsl 1%Z y)) = (lsl 1%Z y)).

Axiom is_sint16_lsl1_sup :
  forall (y:Numbers.BinNums.Z), (16%Z <= y)%Z ->
  ((to_sint16 (lsl 1%Z y)) = 0%Z).

Axiom is_sint32_lnot :
  forall (x:Numbers.BinNums.Z), is_sint32 x ->
  ((to_sint32 (lnot x)) = (lnot x)).

Axiom is_sint32_lxor :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), is_sint32 x ->
  is_sint32 y -> ((to_sint32 (lxor x y)) = (lxor x y)).

Axiom is_sint32_lor :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), is_sint32 x ->
  is_sint32 y -> ((to_sint32 (lor x y)) = (lor x y)).

Axiom is_sint32_land :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), is_sint32 x ->
  is_sint32 y -> ((to_sint32 (land x y)) = (land x y)).

Axiom is_sint32_lsr :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), (0%Z <= y)%Z ->
  is_sint32 x -> ((to_sint32 (lsr x y)) = (lsr x y)).

Axiom is_sint32_lsl1 : ((lsl 1%Z 31%Z) = 2147483648%Z).

Axiom is_sint32_lsl1_inf :
  forall (y:Numbers.BinNums.Z), (0%Z <= y)%Z /\ (y < 31%Z)%Z ->
  ((to_sint32 (lsl 1%Z y)) = (lsl 1%Z y)).

Axiom is_sint32_lsl1_sup :
  forall (y:Numbers.BinNums.Z), (32%Z <= y)%Z ->
  ((to_sint32 (lsl 1%Z y)) = 0%Z).

Axiom is_sint64_lnot :
  forall (x:Numbers.BinNums.Z), is_sint64 x ->
  ((to_sint64 (lnot x)) = (lnot x)).

Axiom is_sint64_lxor :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), is_sint64 x ->
  is_sint64 y -> ((to_sint64 (lxor x y)) = (lxor x y)).

Axiom is_sint64_lor :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), is_sint64 x ->
  is_sint64 y -> ((to_sint64 (lor x y)) = (lor x y)).

Axiom is_sint64_land :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), is_sint64 x ->
  is_sint64 y -> ((to_sint64 (land x y)) = (land x y)).

Axiom is_sint64_lsr :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), (0%Z <= y)%Z ->
  is_sint64 x -> ((to_sint64 (lsr x y)) = (lsr x y)).

Axiom is_sint64_lsl1 : ((lsl 1%Z 63%Z) = 9223372036854775808%Z).

Axiom is_sint64_lsl1_inf :
  forall (y:Numbers.BinNums.Z), (0%Z <= y)%Z /\ (y < 63%Z)%Z ->
  ((to_sint64 (lsl 1%Z y)) = (lsl 1%Z y)).

Axiom is_sint64_lsl1_sup :
  forall (y:Numbers.BinNums.Z), (64%Z <= y)%Z ->
  ((to_sint64 (lsl 1%Z y)) = 0%Z).

Axiom lor_addition :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), ((land x y) = 0%Z) ->
  ((x + y)%Z = (lor x y)).

Axiom lxor_addition :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z), ((land x y) = 0%Z) ->
  ((x + y)%Z = (lxor x y)).

(* Why3 assumption *)
Definition IsArray_uint8 (T:Numbers.BinNums.Z -> Numbers.BinNums.Z) : Prop :=
  forall (i:Numbers.BinNums.Z), is_uint8 (T i).

Parameter sconst: (addr -> Numbers.BinNums.Z) -> Prop.

(* Why3 assumption *)
Definition framed (m:addr -> addr) : Prop :=
  forall (p:addr), ((region (base p)) <= 0%Z)%Z ->
  ((region (base (m p))) <= 0%Z)%Z.

(* Why3 assumption *)
Definition eqmem {a:Type} {a_WT:WhyType a} (m1:addr -> a) (m2:addr -> a)
    (p:addr) (a1:Numbers.BinNums.Z) : Prop :=
  forall (q:addr), included q 1%Z p a1 -> ((m1 q) = (m2 q)).

Parameter havoc:
  forall {a:Type} {a_WT:WhyType a}, (addr -> a) -> (addr -> a) -> addr ->
  Numbers.BinNums.Z -> addr -> a.

Axiom eqmem_included :
  forall {a:Type} {a_WT:WhyType a},
  forall (m1:addr -> a) (m2:addr -> a), forall (p:addr) (q:addr),
  forall (a1:Numbers.BinNums.Z) (b:Numbers.BinNums.Z), included p a1 q b ->
  eqmem m1 m2 q b -> eqmem m1 m2 p a1.

Axiom eqmem_sym :
  forall {a:Type} {a_WT:WhyType a},
  forall (m1:addr -> a) (m2:addr -> a), forall (p:addr),
  forall (a1:Numbers.BinNums.Z), eqmem m1 m2 p a1 -> eqmem m2 m1 p a1.

Axiom havoc_access :
  forall {a:Type} {a_WT:WhyType a},
  forall (m0:addr -> a) (m1:addr -> a), forall (q:addr) (p:addr),
  forall (a1:Numbers.BinNums.Z),
  (separated q 1%Z p a1 -> ((havoc m0 m1 p a1 q) = (m1 q))) /\
  (~ separated q 1%Z p a1 -> ((havoc m0 m1 p a1 q) = (m0 q))).

Parameter cinits: (addr -> Init.Datatypes.bool) -> Prop.

(* Why3 assumption *)
Definition is_init_range (m:addr -> Init.Datatypes.bool) (p:addr)
    (l:Numbers.BinNums.Z) : Prop :=
  forall (i:Numbers.BinNums.Z), (0%Z <= i)%Z /\ (i < l)%Z ->
  ((m (shift p i)) = Init.Datatypes.true).

Parameter set_init:
  (addr -> Init.Datatypes.bool) -> addr -> Numbers.BinNums.Z ->
  addr -> Init.Datatypes.bool.

Axiom set_init_access :
  forall (m:addr -> Init.Datatypes.bool), forall (q:addr) (p:addr),
  forall (a:Numbers.BinNums.Z),
  (separated q 1%Z p a -> ((set_init m p a q) = (m q))) /\
  (~ separated q 1%Z p a -> ((set_init m p a q) = Init.Datatypes.true)).

(* Why3 assumption *)
Definition monotonic_init (m1:addr -> Init.Datatypes.bool)
    (m2:addr -> Init.Datatypes.bool) : Prop :=
  forall (p:addr), ((m1 p) = Init.Datatypes.true) ->
  ((m2 p) = Init.Datatypes.true).

Parameter L_hex_to_bin: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom Q_A0 : ((L_hex_to_bin 48%Z) = 0%Z).

Axiom Q_A1 : ((L_hex_to_bin 49%Z) = 1%Z).

Axiom Q_A2 : ((L_hex_to_bin 50%Z) = 2%Z).

Axiom Q_A3 : ((L_hex_to_bin 51%Z) = 3%Z).

Axiom Q_A4 : ((L_hex_to_bin 52%Z) = 4%Z).

Axiom Q_A5 : ((L_hex_to_bin 53%Z) = 5%Z).

Axiom Q_A6 : ((L_hex_to_bin 54%Z) = 6%Z).

Axiom Q_A7 : ((L_hex_to_bin 55%Z) = 7%Z).

Axiom Q_A8 : ((L_hex_to_bin 56%Z) = 8%Z).

Axiom Q_A9 : ((L_hex_to_bin 57%Z) = 9%Z).

Axiom Q_AA :
  let x := L_hex_to_bin 65%Z in (x = 10%Z) /\ ((L_hex_to_bin 97%Z) = x).

Axiom Q_AB :
  let x := L_hex_to_bin 66%Z in (x = 11%Z) /\ ((L_hex_to_bin 98%Z) = x).

Axiom Q_AC :
  let x := L_hex_to_bin 67%Z in (x = 12%Z) /\ ((L_hex_to_bin 99%Z) = x).

Axiom Q_AD :
  let x := L_hex_to_bin 68%Z in (x = 13%Z) /\ ((L_hex_to_bin 100%Z) = x).

Axiom Q_AE :
  let x := L_hex_to_bin 69%Z in (x = 14%Z) /\ ((L_hex_to_bin 101%Z) = x).

Axiom Q_AF :
  let x := L_hex_to_bin 70%Z in (x = 15%Z) /\ ((L_hex_to_bin 102%Z) = x).

(* Why3 goal *)
Theorem wp_goal :
  forall (t:Numbers.BinNums.Z -> Numbers.BinNums.Z)
    (t1:addr -> Numbers.BinNums.Z)
    (t2:Numbers.BinNums.Z -> Numbers.BinNums.Z) (a:addr)
    (i:Numbers.BinNums.Z) (i1:Numbers.BinNums.Z) (i2:Numbers.BinNums.Z)
    (a1:addr) (a2:addr),
  let x := (16%Z * i)%Z in
  let x1 := offset a2 in
  let x2 := offset a1 in
  let x3 := t1 a2 in
  let x4 := t2 (to_uint8 x3) in
  let x5 := t1 (shift a2 1%Z) in
  let x6 := t2 (to_uint8 x5) in
  let x7 := land 68%Z x4 in
  let x8 := land 68%Z x6 in
  ~ (i2 = 0%Z) -> (x = (lsl i 4%Z)) ->
  ((ZArith.BinInt.Z.quot (x1 + ((-1%Z)%Z * x2)%Z)%Z 2%Z) = 0%Z) ->
  ((ZArith.BinInt.Z.rem (x2 + ((-1%Z)%Z * x1)%Z)%Z 2%Z) = 0%Z) ->
  (0%Z <= i2)%Z -> (0%Z <= i1)%Z -> (0%Z <= i)%Z ->
  ((region (base a1)) <= 0%Z)%Z -> ((region (base a)) <= 0%Z)%Z ->
  (i1 <= 15%Z)%Z -> (i <= 15%Z)%Z -> IsArray_uint8 t2 -> linked t ->
  sconst t1 -> is_sint32 i1 -> is_sint32 i -> is_uint64 i2 ->
  addr_le a1 a2 -> addr_le a1 a1 -> addr_le a a -> is_sint8 x3 ->
  is_uint8 x4 -> is_sint8 x5 -> valid_rw t (shift a 0%Z) (1%Z + i2)%Z ->
  valid_rd t (shift a1 0%Z) (1%Z + (2%Z * i2)%Z)%Z -> is_uint8 x6 ->
  ((x7 = 0%Z) -> (i = (-1%Z)%Z)) ->
  (~ (x7 = 0%Z) -> ((L_hex_to_bin x3) = i)) ->
  ((x8 = 0%Z) -> (i1 = (-1%Z)%Z)) ->
  (~ (x8 = 0%Z) -> ((L_hex_to_bin x5) = i1)) ->
  (forall (a3:addr), addr_lt a3 a2 -> addr_le a1 a3 ->
   ~ ((land 68%Z (t2 (to_uint8 (t1 a3)))) = 0%Z)) ->
  (forall (a3:addr), addr_lt a3 a1 -> addr_le a1 a3 ->
   ~ ((land 68%Z (t2 (to_uint8 (t1 a3)))) = 0%Z)) ->
  ((i1 + x)%Z = (lor i1 x)).
Proof.

Admitted.